 # Site Settings
title: Ziyin Zhong
email: ziyinzhong@ln.hk
description: >- 
  AI & Business Analytics Master Student | Data Analyst | Machine Learning Enthusiast
baseurl: "" 
url: "https://Izzy-byte261.github.io" 
github_username: Izzy-byte261
linkedin_username: "" 
phone: +852 84951466
location: Hong Kong

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation Bar 
header_pages:
  - index.md
  - about.md
  - skills.md
  - projects.md
  - cv.md
  - contact.md

# Footer
footer:
  copyright: "© 2026 Ziyin Zhong. All rights reserved."
